package cmd

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"strings"

	"github.com/parel-cloud/parel-cli/internal/client"
	"github.com/parel-cloud/parel-cli/internal/config"
	"github.com/spf13/cobra"
)

var (
	envOutputPath string
	envForce      bool
)

var envCmd = &cobra.Command{
	Use:   "env",
	Short: "Project-level helpers (Vercel-style)",
}

var envPullCmd = &cobra.Command{
	Use:   "pull",
	Short: "Write the active key + base URL into a .env.local file",
	Long: `Generates a .env.local containing PAREL_API_KEY and PAREL_BASE_URL plus
the OpenAI-compatible aliases so most SDKs work without code changes:

  OPENAI_API_KEY        = (Parel key)
  OPENAI_BASE_URL       = https://api.parel.cloud/v1
  ANTHROPIC_AUTH_TOKEN  = (Parel key)
  ANTHROPIC_BASE_URL    = https://api.parel.cloud/anthropic
  ANTHROPIC_API_KEY     = ""    (must stay empty)`,
	RunE: func(cmd *cobra.Command, args []string) error {
		f, err := config.Load()
		if err != nil {
			return err
		}
		profile, name := f.Resolve(flagProfile)
		if profile.APIKey == "" && flagAPIKey == "" {
			return errors.New("no API key in active profile (run `parel auth login` first)")
		}
		key := flagAPIKey
		if key == "" {
			key = profile.APIKey
		}
		baseURL := flagBaseURL
		if baseURL == "" {
			baseURL = profile.BaseURL
		}
		if baseURL == "" {
			baseURL = client.DefaultBaseURL
		}

		path := envOutputPath
		if path == "" {
			path = ".env.local"
		}
		if _, err := os.Stat(path); err == nil && !envForce {
			return fmt.Errorf("%s exists; pass --force to overwrite", path)
		} else if err != nil && !errors.Is(err, fs.ErrNotExist) {
			return err
		}

		body := strings.Join([]string{
			"# Generated by `parel env pull` — profile: " + name,
			"PAREL_API_KEY=" + key,
			"PAREL_BASE_URL=" + baseURL,
			"OPENAI_API_KEY=" + key,
			"OPENAI_BASE_URL=" + strings.TrimRight(baseURL, "/") + "/v1",
			"ANTHROPIC_AUTH_TOKEN=" + key,
			"ANTHROPIC_BASE_URL=" + strings.TrimRight(baseURL, "/") + "/anthropic",
			`ANTHROPIC_API_KEY=""`,
		}, "\n") + "\n"

		if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
			return err
		}
		fmt.Fprintf(os.Stdout, "Wrote %s (mode 0600)\n", path)
		return nil
	},
}

func init() {
	envPullCmd.Flags().StringVar(&envOutputPath, "output", ".env.local", "destination path")
	envPullCmd.Flags().BoolVar(&envForce, "force", false, "overwrite existing file")

	envCmd.AddCommand(envPullCmd)
	rootCmd.AddCommand(envCmd)
}
